### PR TITLE
Add HTTPS support for ellis

### PR DESCRIPTION
**Pull request by mbt-msw**
By default, nothing is changed, and ellis will listen on port 80.

If an SSL key and certificate are placed in /etc/nginx/ssl/ellis.{key,crt},
then nginx will be configured to provide HTTPS to ellis on port 443 and to
redirect from HTTP on port 80 to HTTPS.

The SSL certificate should have a CN of ellis.$home_domain, or
ellis_hostname should be set in the clearwater config to a valid CN
for the certificate.

### CODE REVIEW

**Comment by bossmc** [comment]
@graemerobertson can you review please (given that you did this for Memento)?  It looks good to me, but I also think it's different to Memento's approach, which should we be using?

**Comment by graemerobertson** [comment]
It looks fine to me. Andy and I discussed the fact that it's different to Memento's approach, and also the differences, but I think we were both happy with that - certainly there was lots of nodding. Passing back to Andy.

**Comment by bossmc** [comment]
Ok, back to Mark to resolve the conflicts then.

**Comment by bossmc** [comment]
Thanks!

**Pull request merged**
